// modules-data.js – single source of truth for Modules page
// Edit this file to add links, weeks, resources; HTML is generated automatically.

window.MODULES_DATA = {
  y1: [
    {
      id: "mci",
      title: "Mathematics for Computing (MCI)",
      tag: "Number Systems • Boolean • Combinatorics",
      meta: "8 weeks • updated Feb 2026",
      chips: ["Exam-heavy", "Daily practice needed"],
      weeks: [
        {
          weekId: "mci-week1",
          label: "Week 1 — Number Systems",
          href: "#",
          summary: "Binary, octal, hexadecimal. Converting between bases. Two's complement for negative numbers.",
          topics: ["Binary ↔ Decimal conversion", "Hexadecimal notation", "Octal system", "Two's complement"],
        },
        {
          weekId: "mci-week2",
          label: "Week 2 — Logic Gates & Boolean Basics",
          href: "#",
          summary: "AND, OR, NOT, NAND, NOR, XOR gates. Truth tables. Basic Boolean expressions.",
          topics: ["AND / OR / NOT gates", "NAND & NOR (universal gates)", "XOR and XNOR", "Truth table construction"],
        },
        {
          weekId: "mci-week3",
          label: "Week 3 — Boolean Algebra",
          href: "#",
          summary: "Boolean identities and laws. Simplifying expressions using De Morgan's laws.",
          topics: ["Boolean identities (identity, null, idempotent)", "De Morgan's Theorem", "Absorption & distribution laws", "Simplifying Boolean expressions"],
        },
        {
          weekId: "mci-week4",
          label: "Week 4 — Karnaugh Maps (K-Maps)",
          href: "#",
          summary: "Using K-maps to minimise Boolean expressions. 2, 3, and 4-variable maps.",
          topics: ["2-variable K-map", "3-variable K-map", "4-variable K-map", "Grouping 1s (SOP form)", "Don't-care conditions"],
        },
        {
          weekId: "mci-week5",
          label: "Week 5 — Sets & Set Operations",
          href: "#",
          summary: "Set notation, union, intersection, complement, Venn diagrams. Power sets.",
          topics: ["Set builder notation", "Union ∪ and Intersection ∩", "Complement and difference", "Venn diagrams", "Power sets"],
        },
        {
          weekId: "mci-week6",
          label: "Week 6 — Counting & Combinatorics",
          href: "#",
          summary: "Multiplication & addition principles. Permutations vs combinations.",
          topics: ["Multiplication principle", "Addition principle", "Permutations P(n,r)", "Combinations C(n,r)", "Factorial notation"],
        },
        {
          weekId: "mci-week7",
          label: "Week 7 — Binomial Theorem",
          href: "#",
          summary: "Expanding binomial expressions. Pascal's triangle. Binomial coefficients.",
          topics: ["Pascal's triangle", "Binomial expansion formula", "Finding specific terms", "Binomial coefficient C(n,k)"],
        },
        {
          weekId: "mci-week8",
          label: "Week 8 — Probability Basics",
          href: "#",
          summary: "Sample spaces, events, probability rules. Conditional probability intro.",
          topics: ["Sample space & events", "P(A) = favourable / total", "Complement rule", "Addition rule P(A∪B)", "Conditional probability intro"],
        },
      ],
      resources: [
        { label: "Past Papers — MCI", href: "https://drive.google.com", icon: "📄" },
        { label: "Boolean Algebra Cheat Sheet", href: "#", icon: "📋" },
        { label: "K-Map Solver (online tool)", href: "https://www.boolean.how", icon: "🔧" },
        { label: "Khan Academy — Combinatorics", href: "https://www.khanacademy.org/math/statistics-probability/counting-permutations-and-combinations", icon: "🎓" },
        { label: "Number Systems Practice", href: "#", icon: "📝" },
      ],
    },
    {
      id: "prg",
      title: "Programming II (PRG)",
      tag: "Java • OOP • Problem Solving",
      meta: "8 weeks • updated Feb 2026",
      chips: ["Lab-heavy", "Build things"],
      weeks: [
        { weekId: "prg-week1", label: "Week 1 — OOP Recap", href: "#", summary: "Review of classes, objects, and methods from Programming I.", topics: ["Classes & objects", "Constructors", "Access modifiers", "Method overloading"] },
        { weekId: "prg-week2", label: "Week 2 — Inheritance", href: "#", summary: "Extending classes, super keyword, method overriding.", topics: ["extends keyword", "super()", "Method overriding", "IS-A relationship"] },
        { weekId: "prg-week3", label: "Week 3 — Interfaces & Abstract Classes", href: "#", summary: "Defining contracts with interfaces, abstract class vs interface.", topics: ["abstract class", "interface", "implements keyword", "Polymorphism"] },
        { weekId: "prg-week4", label: "Week 4 — Arrays & ArrayLists", href: "#", summary: "1D/2D arrays, ArrayList class, iterating collections.", topics: ["Array declaration & init", "2D arrays", "ArrayList<T>", "for-each loop"] },
        { weekId: "prg-week5", label: "Week 5 — Exception Handling", href: "#", summary: "try/catch/finally, throwing exceptions, custom exceptions.", topics: ["try / catch / finally", "throws keyword", "Custom Exception class", "Checked vs unchecked"] },
        { weekId: "prg-week6", label: "Week 6 — File I/O", href: "#", summary: "Reading and writing files in Java.", topics: ["FileReader / FileWriter", "BufferedReader", "Scanner for files", "IOException handling"] },
        { weekId: "prg-week7", label: "Week 7 — Recursion", href: "#", summary: "Recursive methods, base cases, stack behaviour.", topics: ["Base case & recursive case", "Factorial & Fibonacci", "Stack overflow", "When to use recursion"] },
        { weekId: "prg-week8", label: "Week 8 — Mini Project Week", href: "#", summary: "Apply everything — build a small Java application end-to-end.", topics: ["Project planning", "Applying OOP", "Debugging practice", "Code review"] },
      ],
      resources: [
        { label: "Past Papers — PRG", href: "https://drive.google.com", icon: "📄" },
        { label: "Java OOP Cheat Sheet", href: "#", icon: "📋" },
        { label: "W3Schools Java", href: "https://www.w3schools.com/java/", icon: "🎓" },
        { label: "Online Java Compiler (OneCompiler)", href: "https://onecompiler.com/java", icon: "🔧" },
        { label: "NetBeans IDE Download", href: "https://netbeans.apache.org", icon: "⬇️" },
      ],
    },
    {
      id: "dbf",
      title: "Database Fundamentals (DBF)",
      tag: "SQL • ERD • Normalisation",
      meta: "6 weeks • updated Feb 2026",
      chips: ["Lab-heavy", "Hands-on"],
      weeks: [
        { weekId: "dbf-week1", label: "Week 1 — Intro to Databases & SQL", href: "#", summary: "What a DBMS is, relational model basics, first SQL queries.", topics: ["DBMS vs flat files", "Tables, rows, columns", "SELECT, FROM, WHERE", "ORDER BY & LIMIT"] },
        { weekId: "dbf-week2", label: "Week 2 — SQL DDL & DML", href: "#", summary: "Creating and modifying tables. Inserting, updating, deleting data.", topics: ["CREATE TABLE", "ALTER TABLE", "INSERT INTO", "UPDATE & DELETE"] },
        { weekId: "dbf-week3", label: "Week 3 — Joins", href: "#", summary: "Combining tables with INNER, LEFT, RIGHT, and FULL joins.", topics: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "JOIN on multiple conditions"] },
        { weekId: "dbf-week4", label: "Week 4 — ER Diagrams", href: "#", summary: "Entities, attributes, relationships. Drawing and reading ERDs.", topics: ["Entities & attributes", "Primary & foreign keys", "1:1, 1:N, M:N relationships", "ERD notation"] },
        { weekId: "dbf-week5", label: "Week 5 — Normalisation", href: "#", summary: "1NF, 2NF, 3NF. Removing redundancy and anomalies.", topics: ["1NF — eliminate repeating groups", "2NF — remove partial dependencies", "3NF — remove transitive dependencies", "Functional dependency"] },
        { weekId: "dbf-week6", label: "Week 6 — Transactions & Constraints", href: "#", summary: "ACID properties, constraints, integrity rules.", topics: ["PRIMARY KEY & FOREIGN KEY", "NOT NULL, UNIQUE, CHECK", "ACID properties", "Referential integrity"] },
      ],
      resources: [
        { label: "Past Papers — DBF", href: "https://drive.google.com", icon: "📄" },
        { label: "SQL Quick Reference", href: "https://www.w3schools.com/sql/", icon: "📋" },
        { label: "MySQL Workbench Download", href: "https://www.mysql.com/products/workbench/", icon: "⬇️" },
        { label: "SQLZoo — Practice Queries", href: "https://sqlzoo.net", icon: "🔧" },
        { label: "ERDplus — Draw ERDs Free", href: "https://erdplus.com", icon: "🔧" },
      ],
    },
    {
      id: "dtn",
      title: "Data Networks (DTN)",
      tag: "TCP/IP • OSI • Routing",
      meta: "6 weeks • updated Feb 2026",
      chips: ["Exam-heavy", "Conceptual"],
      weeks: [
        { weekId: "dtn-week1", label: "Week 1 — Network Fundamentals", href: "#", summary: "Types of networks, topologies, transmission media.", topics: ["LAN / WAN / MAN", "Bus, Star, Ring, Mesh topologies", "Guided vs unguided media", "Bandwidth & throughput"] },
        { weekId: "dtn-week2", label: "Week 2 — OSI Model", href: "#", summary: "The 7 layers of OSI — what each does and why it exists.", topics: ["7 OSI layers (Physical → Application)", "PDU per layer", "Encapsulation", "Layer responsibilities"] },
        { weekId: "dtn-week3", label: "Week 3 — TCP/IP Model", href: "#", summary: "OSI vs TCP/IP, the 4-layer model, common protocols.", topics: ["4 TCP/IP layers", "OSI ↔ TCP/IP mapping", "IP, TCP, UDP", "DNS, HTTP, FTP"] },
        { weekId: "dtn-week4", label: "Week 4 — IP Addressing", href: "#", summary: "IPv4 addresses, classes, subnetting basics.", topics: ["IPv4 format (dotted decimal)", "Address classes A/B/C", "Subnet mask", "CIDR notation intro"] },
        { weekId: "dtn-week5", label: "Week 5 — Routing & Switching", href: "#", summary: "How routers forward packets, routing tables, switches vs hubs.", topics: ["Router vs Switch vs Hub", "Routing table", "Static vs dynamic routing", "MAC address & ARP"] },
        { weekId: "dtn-week6", label: "Week 6 — Ports & Protocols", href: "#", summary: "Port numbers, well-known ports, TCP vs UDP behaviour.", topics: ["Port numbers (0–65535)", "Well-known ports (80, 443, 22…)", "TCP handshake (SYN/SYN-ACK/ACK)", "UDP — when and why"] },
      ],
      resources: [
        { label: "Past Papers — DTN", href: "https://drive.google.com", icon: "📄" },
        { label: "OSI vs TCP/IP Cheat Sheet", href: "#", icon: "📋" },
        { label: "Cisco Packet Tracer (free)", href: "https://www.netacad.com/courses/packet-tracer", icon: "🔧" },
        { label: "Professor Messer Networking (YouTube)", href: "https://www.youtube.com/@professormesser", icon: "🎓" },
        { label: "Subnet Calculator", href: "https://www.subnet-calculator.com", icon: "🔧" },
      ],
    },
    {
      id: "iss",
      title: "Information Systems Security (ISS)",
      tag: "CIA Triad • Threats • Controls",
      meta: "5 weeks • updated Feb 2026",
      chips: ["Theory", "Conceptual"],
      weeks: [
        { weekId: "iss-week1", label: "Week 1 — CIA Triad", href: "#", summary: "Confidentiality, Integrity, Availability — the foundation of information security.", topics: ["Confidentiality", "Integrity", "Availability", "Real-world CIA examples"] },
        { weekId: "iss-week2", label: "Week 2 — Common Threats & Attacks", href: "#", summary: "Malware types, social engineering, network attacks.", topics: ["Malware (virus, worm, trojan, ransomware)", "Phishing & social engineering", "DoS / DDoS", "Man-in-the-middle attacks"] },
        { weekId: "iss-week3", label: "Week 3 — Security Controls", href: "#", summary: "Preventive, detective, and corrective controls.", topics: ["Preventive controls (firewalls, encryption)", "Detective controls (IDS, logs)", "Corrective controls (backups, patches)", "Physical vs logical controls"] },
        { weekId: "iss-week4", label: "Week 4 — Cryptography Basics", href: "#", summary: "Symmetric vs asymmetric encryption. Hashing. Certificates.", topics: ["Symmetric encryption (AES)", "Asymmetric encryption (RSA)", "Hashing (MD5, SHA)", "Digital signatures & PKI basics"] },
        { weekId: "iss-week5", label: "Week 5 — Risk & Policy", href: "#", summary: "Risk assessment, security policies, compliance basics.", topics: ["Risk = Threat × Vulnerability × Impact", "Risk mitigation strategies", "Security policies", "GDPR / compliance intro"] },
      ],
      resources: [
        { label: "Past Papers — ISS", href: "https://drive.google.com", icon: "📄" },
        { label: "CIA Triad Summary", href: "#", icon: "📋" },
        { label: "TryHackMe — Free Security Labs", href: "https://tryhackme.com", icon: "🔧" },
        { label: "CompTIA Security+ Concepts (YouTube)", href: "https://www.youtube.com/@professormesser", icon: "🎓" },
      ],
    },
  ],
  y2: [],
  y3: [],
};

// Checklist labels (same for every week)
window.MODULES_CHECKLIST_ITEMS = [
  { cb: "playlist", label: "Watched playlist" },
  { cb: "notes",    label: "Read notes" },
  { cb: "exercises", label: "Did exercises" },
  { cb: "pastpaper", label: "Past paper attempted" },
];
